---
- name: Deploy Library Management System (Spring Boot)
  hosts: all
  become: yes
  vars:
    docker_image: "{{ docker_image | default('library-management-system:latest') }}"
    app_port: 8080
    container_name: library-app

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Stop and remove existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove existing image
      docker_image:
        name: "{{ docker_image }}"
        state: absent
      ignore_errors: yes

    - name: Pull latest Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes

    - name: Run the application container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ app_port }}:8080"
        env:
          JAVA_OPTS: "-Xmx512m -Xms256m"

    - name: Wait for application to start
      wait_for:
        port: "{{ app_port }}"
        delay: 5
        timeout: 60

    - name: Check application health
      uri:
        url: "http://localhost:{{ app_port }}/books"
        method: GET
        status_code: 200
      register: health_check
      retries: 3
      delay: 5

    - name: Display deployment status
      debug:
        msg: "Application deployed successfully to http://localhost:{{ app_port }}"

    - name: Display container logs
      shell: docker logs {{ container_name }} --tail 20
      register: container_logs

    - name: Show container logs
      debug:
        var: container_logs.stdout_lines 